#!/usr/bin/env bash
#
# Regenerates web/data.js by embedding the sample datasets from app/data/ASCII.
#
# The page has to work when opened straight from the filesystem (file://), where browsers
# refuse to fetch sibling files, so the data is embedded rather than loaded at runtime.
# Re-run this whenever app/data/ASCII changes.
#
# Usage: scripts/build-web-data.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA="$REPO_ROOT/app/data/ASCII"
OUT="$REPO_ROOT/web/data.js"

emit_dataset() {
    local name="$1" file="$2"
    printf '  %s: [\n' "$name"
    # One JSON string per fixed width record; carriage returns stripped, blanks skipped.
    tr -d '\r' < "$file" | awk 'length($0) > 0 { gsub(/\\/, "\\\\"); gsub(/"/, "\\\""); printf "    \"%s\",\n", $0 }'
    printf '  ].join("\\n"),\n'
}

mkdir -p "$(dirname "$OUT")"

{
    echo "// Generated by scripts/build-web-data.sh - do not edit by hand."
    echo "// Source: app/data/ASCII (the CardDemo sample datasets, fixed width records)."
    echo "window.CARDDEMO_DATA = {"
    emit_dataset "tcatbal"  "$DATA/tcatbal.txt"
    emit_dataset "acctdata" "$DATA/acctdata.txt"
    emit_dataset "cardxref" "$DATA/cardxref.txt"
    emit_dataset "discgrp"  "$DATA/discgrp.txt"
    echo "};"
} > "$OUT"

echo "Wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
